name: gokapi_quick_upload
description: "Quick Upload to gokapi from the share sheet"
publish_to: 'none'
version: 1.0.1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  receive_sharing_intent: ^1.8.1
  flutter_secure_storage: ^10.0.0
  http: ^1.6.0
  http_parser: ^4.1.2
  file_picker: ^11.0.2
  share_plus: ^12.0.2
  mime: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
